name: Publish Artifacts
on:
  push:
    tags:
      - '*'

env:
  GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
  GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}

jobs:
  PublishGradlePlugin:
    runs-on: ubuntu-latest
    if: ${{ !endsWith(github.ref_name, '-SNAPSHOT') }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Publish to Gradle Plugin Portal
        run: make publish-gradle-plugin

  DispatchReleaseEvent:
    runs-on: ubuntu-latest
    needs: [PublishGradlePlugin]
    if: ${{ always() && needs.PublishGradlePlugin.result == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Dispatch Release Event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: kensa-dev/kensa
          event-type: kensa-release
          client-payload: '{"version": "${{ github.ref_name }}"}'
